TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
DB += Neslab_rte.db
DB += Oxford_E500.db
DB += VAT_Control.db
DB += TE_TC.db
DB += BK_1787B.db

DB += Labjack_T7-ai.db
DB += Labjack_T7-ao-all.db
DB += Labjack_T7-di.db
DB += Labjack_T7-do.db
DB += Labjack_T7-tc.db
DB += Labjack_T7-ef-a.db

DB += depo_plc.db

DB += asynRecord.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

